### ISSUE TITLE
Bug:  Sporadische Fehler beim Speichern von Assets

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#348]
**Beschreibung**

Marcel:
Beim Speichern eines neuen Assets erscheint "Internal Server Error", Asset kann nicht gespeichert werden.
Dito beim Bearbeiten von Assets, auf INT und auf DEV.
Fehler jedoch nicht konsistent auftretend, ggf. von Workgroup und/oder Löschen-Aktion abhängig.

Server Error Log:
```
 2024-11-13T15:00:37.058Z    ERROR   main  PrismaClientKnownRequestError: 
Invalid `prisma.asset.create()` invocation:


An operation failed because it depends on one or more records that were required but not found. No 'AssetKindItem' record(s) (needed to inline the relation on 'Asset' record(s)) was found for a nested connect on one-to-many relation 'AssetToAssetKindItem'.
    at Rn.handleRequestError (/app/node_modules/.prisma/client/runtime/library.js:174:7325)
    at Rn.handleAndLogRequestError (/app/node_modules/.prisma/client/runtime/library.js:174:6754)
    at Rn.request (/app/node_modules/.prisma/client/runtime/library.js:174:6344)
    at async AssetEditRepo.create (/app/main.js:1:85230)
    at async AssetEditController.create (/app/main.js:34:12491)
    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```
```
 2024-11-13T14:23:46.304Z    ERROR   main  PrismaClientKnownRequestError: 
Invalid `prisma.asset.update()` invocation:


Foreign key constraint failed on the field: `asset_asset_kind_item_code_fkey (index)`
    at Rn.handleRequestError (/app/node_modules/.prisma/client/runtime/library.js:174:7325)
    at Rn.handleAndLogRequestError (/app/node_modules/.prisma/client/runtime/library.js:174:6754)
    at Rn.request (/app/node_modules/.prisma/client/runtime/library.js:174:6344)
    at async /app/main.js:1:86555
    at async Proxy._transactionWithCallback (/app/node_modules/.prisma/client/runtime/library.js:177:9822)
    at async AssetEditRepo.update (/app/main.js:1:86506)
    at async AssetEditController.update (/app/main.js:34:12893)
    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by mPfifi** [comment]
Ich konnte den Fehler nicht mehr provozieren, auch mit Löschen von Assets mit nur einem Eintrag unter "Art" oder "Thema" nicht mehr. Der Begriff verschwindet auch nicht mehr aus der DropDown-Liste.

**Comment by mPfifi** [comment]
Fehler tritt nicht mehr auf, Begriffe/Einträge werden nicht weiter aus Listen entfernt.
